server:
  port: 12000
spring:
  application:
    name: ppsweet-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/*******/PPSweet.git
  rabbitmq:
    host: 192.168.182.143
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh